# Generated by Django 3.1.6 on 2021-03-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210310_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
