# Generated by Django 3.1.6 on 2021-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_descriplib_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(default='')),
                ('Descripcion', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('Nacionalidad', models.TextField(default='')),
                ('F_Muerte', models.TextField(default='')),
            ],
        ),
    ]
